In [4]:
import numpy as np
!pip install pandas

In [5]:
class Graph:

    def __init__(self,n,m,l):
        self.n = n
        self.m = m
        self.l = l

    def getGraph(self):
        matrix = []
        #s = np.matrix()
        
        for i in range(self.n):
            a = []
            for j in range(self.n):
                if abs(i-j) in self.l:
                    a.append(1)
                else:
                    a.append(0)
            a = np.array(a)
            matrix.append(a)
        matrix = np.matrix(matrix)
        
        return matrix

In [6]:
graphs_file = open(r'C:\Users\mrogi\Desktop\završni\graphs.txt')
graphs_input = graphs_file.readlines()


chr_nums_file = open(r'C:\Users\mrogi\Desktop\završni\chr_nums.txt')
chr_nums = chr_nums_file.readlines()

In [7]:
graphs = []

for i in range(len(chr_nums)):
    chr_nums[i] = chr_nums[i].strip('\n')
    chr_nums[i] = int(chr_nums[i])
    chr_nums[i] /= 20

for i in range(len(graphs_input)):
    graphs_input[i] = graphs_input[i].strip(' \n')
    
    if i % 3 != 2:
        graphs_input[i] = int(graphs_input[i])
    else:
        graphs_input[i] = graphs_input[i].split(" ")
        
        for j in range(len(graphs_input[i])):
            graphs_input[i][j] = int(graphs_input[i][j])

        tmp = Graph(graphs_input[i-2], graphs_input[i-1], graphs_input[i])
        
        
        graphs.append(tmp.getGraph())

In [8]:
import numpy as np
#graphs = np.matrix(graphs)


In [9]:
#for i in range(len(graphs)):
    #graphs[i] = np.matrix(graphs[i])
    #graphs[i] = graphs[i].reshape(20,20)
#graphss = graphs.reshape((len(graphs), 20, 20))
#graphs = graphss
for i in range(1000):
    graphs[i]=np.pad(graphs[i],[(0,20-len(graphs[i])),(0,20-len(graphs[i]))],mode='constant')

In [10]:
from sklearn.model_selection import train_test_split

x_train, x_rem, y_train, y_rem = train_test_split(graphs, chr_nums, train_size=0.8)

test_size = 0.5
x_valid, x_test, y_valid, y_test = train_test_split(x_rem, y_rem, test_size=0.5)

#x_train = np.matrix(x_train)
x_train = np.expand_dims(x_train, axis=-1) 
#y_train = np.matrix(y_train)
y_train = np.expand_dims(y_train, axis=-1) 
#x_valid = np.matrix(x_valid)
x_valid = np.expand_dims(x_valid, axis=-1) 
#y_valid = np.matrix(y_valid)
y_valid = np.expand_dims(y_valid, axis=-1) 
#x_test = np.matrix(x_test)
x_test = np.expand_dims(x_test, axis=-1) 
#y_test = np.matrix(y_test)
y_test = np.expand_dims(y_test, axis=-1)

print(x_test)
print(y_test)

[[[[0]
   [0]
   [1]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[1]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 [[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 [[[0]
   [1]
   [1]
   ...
   [0]
   [0]
   [0]]

  [[1]
   [0]
   [1]
   ...
   [0]
   [0]
   [0]]

  [[1]
   [1]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 ...


 [[[0]
   [1]
   [1]
   ...
   [0]
   [0]
   [0]

In [11]:
import tensorflow as tf
#from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, InputLayer
from tensorflow.keras.layers import Conv2D, MaxPooling2D, LeakyReLU


In [12]:
model = Sequential()

model.add(InputLayer(input_shape = (20, 20, 1)))
model.add(Conv2D(512, kernel_size=(3, 3),
                 activation='relu'))
#model.add(LeakyReLU(0.05))
model.add(MaxPooling2D(2))
#model.add(Dropout(0.25))
#model.add(Flatten())

model.add(Conv2D(64, kernel_size=(3, 3),
                 activation='relu'))
#model.add(LeakyReLU(0.05))
model.add(MaxPooling2D(2))

model.add(Flatten())
model.add(Dense(300, activation='relu'))
model.add(Dropout(0.25))

#model.add(LeakyReLU(0.05))

model.add(Dense(300, activation='relu'))
model.add(Dropout(0.25))

model.add(Dense(19, activation='relu')) #istraži


In [16]:
from tensorflow.keras.callbacks import EarlyStopping

#model = Cnn()
model.compile(optimizer = tf.keras.optimizers.Adam(), loss = tf.keras.losses.MAE,  metrics=[tf.keras.metrics.MeanAbsoluteError()]) #istraži
#model.fit(x_train, y_train, validation_data= (x_valid, y_valid), 
              #        epochs = 125, verbose = 0)

#model.evaluate(x = x_valid, y = y_valid, verbose=0)
early_stopping_callback = EarlyStopping(patience = 50, monitor = 'val_loss', restore_best_weights = True, 
                                        min_delta = 0.000001)

model.fit(x_train, y_train, validation_data= (x_valid, y_valid), 
                      epochs = 1500, verbose = 0,
                      callbacks = [early_stopping_callback])
model.evaluate(x = x_valid, y = y_valid)
model.predict(x_test)

100/100 [==============================] - 0s 3ms/sample - loss: 0.0120 - mean_absolute_error: 0.0120


array([[0.20451264, 0.2009266 , 0.20106044, ..., 0.20058537, 0.20146841,
        0.19949275],
       [0.10091639, 0.10066739, 0.10122435, ..., 0.10090835, 0.10076287,
        0.10104112],
       [0.19231765, 0.19123644, 0.19109648, ..., 0.19019732, 0.19087222,
        0.19133648],
       ...,
       [0.2562344 , 0.2513363 , 0.2537598 , ..., 0.25225577, 0.25153682,
        0.251268  ],
       [0.24599919, 0.24698699, 0.24598116, ..., 0.24440965, 0.24697898,
        0.24173012],
       [0.25201517, 0.24717543, 0.25134215, ..., 0.2481935 , 0.24780723,
        0.24972782]], dtype=float32)

In [17]:
l = model.predict(x_test)
l
tmp = []
for i in range(len(l)):
    tmp.append(np.sum(l[i]))
tmp

[3.8211846,
 1.91935,
 3.623996,
 3.5667453,
 4.3000445,
 2.8828201,
 4.127881,
 3.9280694,
 3.128548,
 1.9049115,
 5.8651576,
 4.122967,
 3.0631108,
 1.9049115,
 3.1394458,
 3.7090116,
 2.8755674,
 4.673271,
 2.1344428,
 4.522029,
 1.9049115,
 4.071552,
 3.305691,
 7.073585,
 1.9049115,
 2.7464328,
 3.786277,
 2.893517,
 3.5529916,
 3.3558543,
 1.9049115,
 2.9280832,
 5.084163,
 3.7487614,
 2.8634152,
 3.1343043,
 4.743453,
 1.9074578,
 1.9049115,
 1.9049115,
 1.9049115,
 3.5413058,
 1.9049115,
 1.9049115,
 1.9049115,
 1.9049115,
 2.8724914,
 1.9049115,
 1.9049115,
 4.93543,
 2.8552434,
 1.9049115,
 2.8328555,
 3.9860587,
 1.9049115,
 2.105322,
 1.9049115,
 1.9049115,
 6.66418,
 2.905836,
 6.7094007,
 1.905637,
 4.2049513,
 2.174777,
 4.7632737,
 2.8558776,
 1.9049115,
 1.9049115,
 6.093728,
 3.8051322,
 1.9049115,
 2.87759,
 5.4441223,
 3.0396457,
 3.773938,
 1.9049115,
 2.7241406,
 1.9049115,
 5.236672,
 1.9049115,
 1.9049115,
 5.827589,
 5.1769066,
 5.7225366,
 5.5632825,
 4.655849

In [28]:
import pandas
def create_df_output(clf, y, df):
    for i in range(len(y)):
        y[i] = y[i][0]
    yy = []
    for i in range(len(y)):
        yy.append(y[i][0] * 20)
    '''
    dff = []
    for i in range(len(df)):
        tmp = []
        for j in range(20):
            tmpp = []
            for k in range(20):
                tmpp.append(df[i][j][k][0])
            tmpp = np.array(tmpp)
            tmp.append(tmpp)
        dff.append(tmp)
    '''
    df_output = pandas.DataFrame()
    df_output['actual'] = yy
    #print(df_output)
    l = model.predict(x_test)
    l
    tmp = []
    for i in range(len(l)):
        tmp.append(np.sum(l[i]))
    df_output['pred'] = tmp
    df_output['error'] = df_output.actual - df_output.pred
    df_output['abs_error'] = np.abs(df_output['error'])
    print(df_output)
    return(df_output)

In [29]:
chr_nums = np.array(chr_nums)
#print(chr_nums)
#out = create_df_output(model, y_test, x_test)
#print(y_test[0][0])
out = create_df_output(model, y_test, x_test)

    actual      pred     error  abs_error
0      5.0  3.821185  1.178815   1.178815
1      2.0  1.919350  0.080650   0.080650
2      4.0  3.623996  0.376004   0.376004
3      3.0  3.566745 -0.566745   0.566745
4      4.0  4.300045 -0.300045   0.300045
..     ...       ...       ...        ...
95     2.0  1.904912  0.095088   0.095088
96     6.0  4.633928  1.366072   1.366072
97     5.0  4.789382  0.210618   0.210618
98     5.0  4.654244  0.345756   0.345756
99     5.0  4.722372  0.277628   0.277628

[100 rows x 4 columns]


In [30]:
def compute_pl(df, diff):
    '''
    Computes the metric p_l, which shows the percentage of records in the dataset
    with an absolute error <= diff, a user input parameter (typically 0.5 or 1)
    '''
    print("% within ", diff, "of true chromatic#:", 
          100 * np.sum(df['abs_error']<= diff) / np.sum(df['abs_error']>= 0))

In [37]:
#print(df_output)
compute_pl(out,0.5)

% within  0.5 of true chromatic#: 77.0
